# Generated by Django 4.1.5 on 2023-01-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('cartoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa'),
        ),
    ]
